/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f5f3ee",
        "on-primary": "#ffffff",
        "surface-dim": "#dbdad5",
        "background": "#fbf9f4",
        "error": "#ba1a1a",
        "surface-container-highest": "#e4e2dd",
        "on-surface-variant": "#444840",
        "inverse-primary": "#bbcca9",
        "on-error": "#ffffff",
        "on-background": "#1b1c19",
        "surface-bright": "#fbf9f4",
        "surface-tint": "#536346",
        "on-primary-fixed-variant": "#3c4b30",
        "on-primary-fixed": "#121f08",
        "primary": "#455538",
        "on-secondary-fixed": "#360f02",
        "primary-fixed": "#d6e8c3",
        "on-tertiary-fixed": "#001e2b",
        "inverse-on-surface": "#f2f1ec",
        "primary-fixed-dim": "#bbcca9",
        "on-secondary": "#ffffff",
        "outline": "#75786f",
        "surface": "#fbf9f4",
        "outline-variant": "#c5c8bd",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#2f4a58",
        "surface-variant": "#e4e2dd",
        "on-primary-container": "#dceec9",
        "secondary-fixed": "#ffdbce",
        "tertiary-fixed-dim": "#aecbdb",
        "surface-container-high": "#eae8e3",
        "on-tertiary": "#ffffff",
        "tertiary": "#395462",
        "secondary-container": "#ffb59a",
        "on-surface": "#1b1c19",
        "tertiary-fixed": "#cae7f8",
        "error-container": "#ffdad6",
        "inverse-surface": "#30312e",
        "secondary": "#88503a",
        "on-secondary-fixed-variant": "#6c3925",
        "on-tertiary-container": "#d0edfe",
        "on-secondary-container": "#7a442f",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#516c7b",
        "secondary-fixed-dim": "#ffb59a",
        "primary-container": "#5d6d4f",
        "surface-container": "#f0eee9"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      spacing: {
        "container-margin": "24px",
        "gutter": "16px",
        "section-gap-md": "32px",
        "base": "8px",
        "section-gap-lg": "64px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Public Sans", "sans-serif"],
        "headline-lg": ["Public Sans", "sans-serif"],
        "label-md": ["Public Sans", "sans-serif"],
        "headline-display": ["Public Sans", "sans-serif"],
        "body-lg": ["Public Sans", "sans-serif"],
        "body-md": ["Public Sans", "sans-serif"],
        "caption": ["Public Sans", "sans-serif"],
        "headline-md": ["Public Sans", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "600"}],
        "headline-display": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "caption": ["12px", {"lineHeight": "16px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}]
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
